### ISSUE TITLE
CWL didn't come from GA4GH, please make this clear in the README

### ISSUE THREAD

**Issue by mr-c** [ga4gh/workflow-execution-schemas#7]
"From within this group, two approaches have emerged, resulting in the production of two distinct but complementary specifications: the Common Workflow Language, or CWL, and the Workflow Description Language, or WDL. "

Additionally:

The characterization that "[t]he CWL approach emphasizes execution features and machine-readability, and serves a core target audience of software and platform developers. The WDL approach, on the other hand, emphasizes scripting and human-readability, and serves a core target audience of research scientists" doesn't seem to be true, nor serve a useful purpose and should be removed.

Thanks!

**Comment by geoffjentry** [comment]
The part which you quoted doesn't imply (to me at least) that it came from GA4GH. Further the portion which you quoted appears to capture reality IMO.

**Comment by denis-yuen** [comment]
FYI, I think this paragraph was introduced here 
https://github.com/ga4gh/tool-registry-schemas/commit/122e16702d3d42163eca20ae6f0350c08879a4e9

**Comment by mr-c** [comment]
@geoffjentry I've [updated the issue](https://github.com/ga4gh/workflow-execution-schemas/issues/7#issue-199876027) to add the quote that implied that CWL & WDL flowed from GA4GH.

As for the comparison, we could debate it but regardless of our personal views I don't see what purpose it serves :-)

**Comment by geoffjentry** [comment]
@denis-yuen yes, we had complained that the previous blurb implied GA4GH endorsement of CWL which as @mr-c is fond of pointing out is untrue.

**Comment by geoffjentry** [comment]
Thinking about it a bit IMO the right thing to do here is to remove all reference to CWL and WDL as neither are GA4GH standards (neither created by nor for the GA4GH)

**Comment by denis-yuen** [comment]
As a third party, I think it makes sense to remove the comparison of CWL and WDL, especially if there is no agreement on what the difference is between the two.

I do think it makes sense to at least mention the two, if only to give people who stumble on the page an idea what the "Containers and Workflows Task Team" is interested in, but it could be done in the form of a  list of things that we're interested in but played no role in founding like Docker, AWS, Google Genomics, etc. Except worded better.

**Comment by geoffjentry** [comment]
@denis-yuen I like that last idea. I'd like to think that we're interested in more than schemes of describing workflows (heck, "containers" is in the name!).

Also, IMO now that we (as CWF) have products of our own, e.g. the tool repository api, task execution api, etc - I think those things should be brought more to the forefront.

**Comment by mr-c** [comment]
Since it has been a month I issued some PRs to remove the paragraphs. It makes sense to remove them now and add new text later when consensus is reached.

If this seems a bit abrupt, please remember that the last time this happened the imprecision persisted for three months, was fixed, and then later returned for six months. In the meantime it was propagated into a published master's thesis : https://arxiv.org/pdf/1702.02999.pdf#page=67 (Section 5.4, at the bottom of the page)

BTW, I :heart: you all! There is a PR to add backlinks to this community from the CWL homepage that will get merged ASAP: https://github.com/common-workflow-language/common-workflow-language/blob/1d5c5b9d262d06836f2b880d82f9824f772cafb4/README.md#projects-the-cwl-community-is-participating-in

**Comment by vdauwera** [comment]
I proposed a rewrite as a review comment in @mr-c's PR. For now it's a pretty minimal mention of the two languages but it could be expanded to add more information about each, as well as other components the group is interested in.

**Comment by geoffjentry** [comment]
@mr-c I agree with what @denis-yuen said above and we should do away with any comparisons of CWL/WDL. I know I for one take issue with the way you framed the compare & contrast and I'm sure you'd do the same if I were to write it. I know you'd disagree w/ the one @vdauwera because you've already complained in this thread.

I would prefer to see (in all of the PRs you just opened) something like what Denis said:

```I do think it makes sense to at least mention the two, if only to give people who stumble on the page an idea what the "Containers and Workflows Task Team" is interested in, but it could be done in the form of a list of things that we're interested in but played no role in founding like Docker, AWS, Google Genomics, etc. Except worded better.```

**Comment by mr-c** [comment]
@geoffjentry Fair enough, I've reset https://github.com/ga4gh/workflow-execution-schemas/pull/10 back to the original commit which removes the problem paragraphs.

As I'm not a GA4GH member, I can't say what this GA4GH task team is interested in and I'm not interested in further delaying a fix.

Please merge the paragraph removal ASAP.

**Comment by denis-yuen** [comment]
@geoffjentry @mr-c  Was there a misunderstanding somewhere along the line? https://github.com/mr-c/tool-registry-schemas/commit/84151c7edef8b3a1224ce6f70c0d67eac6c4a5e1 seemed generic enough to be acceptable by both sides, but was removed subsequently. 

Are both of you ok with it?

**Comment by mr-c** [comment]
This was finally fixed; thanks all
